/**
 * Claude Code hook script source code, embedded as string constants so we
 * can write them out from `syncManagedHooks()`.
 *
 * Both scripts read a single JSON event payload from stdin and emit a JSON
 * response on stdout. They `exit 0` even on internal failure (fail-open) so
 * a misbehaving hook never bricks a Claude session — denying actions stays
 * an explicit signal carried inside the JSON response.
 *
 * Naming convention: managed scripts must live in `.claude/hooks/aiw-*.sh`
 * so `sync.ts` can identify and replace them without touching user-authored
 * hooks.
 */

/** PreToolUse hook: blocks dangerous Bash commands. */
export const BLOCK_DANGEROUS_BASH_SH = `#!/usr/bin/env bun
// Auto-generated by ai-workspace-v2. Edit sync.ts / scripts.ts to change.

const stdin = await Bun.stdin.text();
let payload;
try {
  payload = JSON.parse(stdin);
} catch {
  process.exit(0); // fail-open
}

const command = payload?.tool_input?.command;
if (typeof command !== "string") {
  process.exit(0);
}

const PATTERNS = [
  {
    re: /\\brm\\s+(?:-[a-zA-Z]*r[a-zA-Z]*f|-[a-zA-Z]*f[a-zA-Z]*r)\\s+\\/[^\\s]*/,
    reason: "rm -rf with an absolute path is blocked. Use a relative path or disable hooks.blockDangerousBash in config.yml.",
  },
  {
    re: /\\bgit\\s+push\\s+.*?--force(?!-with-lease)\\b/,
    reason: "git push --force is blocked. Use --force-with-lease, or disable hooks.blockDangerousBash in config.yml.",
  },
  {
    re: /\\bgit\\s+reset\\s+--hard\\b/,
    reason: "git reset --hard is blocked. Verify the change is intentional, then disable hooks.blockDangerousBash in config.yml.",
  },
];

for (const { re, reason } of PATTERNS) {
  if (re.test(command)) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: reason,
      },
    }));
    process.exit(0);
  }
}

process.exit(0);
`;

/** SessionStart hook: injects current git branch and short status. */
export const SESSION_START_GIT_SH = `#!/usr/bin/env bun
// Auto-generated by ai-workspace-v2. Edit sync.ts / scripts.ts to change.

async function run(cmd: string[]): Promise<string> {
  try {
    const proc = Bun.spawn(cmd, { stdout: "pipe", stderr: "pipe" });
    const out = await new Response(proc.stdout).text();
    await proc.exited;
    if (proc.exitCode !== 0) return "";
    return out.trim();
  } catch {
    return "";
  }
}

const branch = await run(["git", "branch", "--show-current"]);
const status = await run(["git", "status", "--short"]);

if (!branch && !status) {
  process.exit(0);
}

const lines: string[] = [];
if (branch) lines.push(\`Current git branch: \${branch}\`);
if (status) {
  lines.push("git status --short:");
  lines.push(status);
} else if (branch) {
  lines.push("git status --short: (clean)");
}

process.stdout.write(JSON.stringify({
  hookSpecificOutput: {
    hookEventName: "SessionStart",
    additionalContext: lines.join("\\n"),
  },
}));
process.exit(0);
`;

/** File names for managed hook scripts (relative to `.claude/hooks/`). */
// .ts extension is intentional: Bun's loader uses the extension to pick the
// transpiler, so .sh would skip TypeScript parsing. Claude Code invokes the
// command via execve which honours the shebang regardless of extension.
export const MANAGED_SCRIPT_NAMES = {
  blockDangerousBash: "aiw-block-dangerous-bash.ts",
  sessionStartGit: "aiw-session-start-git.ts",
} as const;

/** Prefix that identifies managed hook command paths in settings.local.json. */
export const MANAGED_COMMAND_PREFIX = "$CLAUDE_PROJECT_DIR/.claude/hooks/aiw-";
